### ISSUE TITLE
New release (PyPI)

### ISSUE THREAD

**Issue by Jamim** [bitlabstudio/django-user-media#13]
Hi,

Could you please push a new version of the `django-user-media` with all recent changes to the PyPI?
Some migrations are missed in version `1.2.4`, so it makes me using `-e git://github.com/bitmazk/django-user-media@bd09a2762e73fa6c5d710e4dfbe764841e831a7c#egg=django_user_media` instead of `django-user-media==1.2.5` at `requirements.txt`.

Thanks!

**Comment by Tyrdall** [comment]
@Jamim Sure! https://pypi.python.org/pypi/django-user-media/1.2.5
